run:
  timeout: 5m
  go: '1.24'

linters-settings:
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/bezineb5/go-build-hat
  govet:
    enable:
      - atomicalign
      - deepequalerrors
      - findcall
      - nilness
      - reflectvaluecompare
      - shadow
      - sortslice
      - unusedwrite
  misspell:
    locale: US
  nolintlint:
    allow-leading-space: true
    allow-unused: false
    require-explanation: false
    require-specific: false

linters:
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - goconst
        - dupl
        - gocyclo
    - path: examples/
      linters:
        - gomnd
        - goconst
        - dupl
        - gocyclo
    - text: "Error return value of .((os\\.)?std(out|err)\\..*|.*Close|.*Flush|os\\.Remove(All)?|.*printf?|os\\.(Un)?Setenv). is not checked"
      linters:
        - errcheck
    - text: "exported (.+) should have comment or be unexported"
      linters:
        - golint
